/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ODHActivityPoi } from '../models';
import { SmgPoiTypes } from '../models';
/**
 * ODHActivityPoiApi - axios parameter creator
 * @export
 */
export const ODHActivityPoiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {        
        /**
         * 
         * @summary GET ODHActivityPoi Types List
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetAllODHActivityPoiTypesList: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ODHActivityPoiTypes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth2", [""])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET ODHActivityPoi Types Single
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetAllODHActivityPoiTypesSingle: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling oDHActivityPoiGetAllODHActivityPoiTypesSingle.');
            }
            const localVarPath = `/v1/ODHActivityPoiTypes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth2", [""])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET ODHActivityPoi List
         * @param {number} [pagenumber] Pagenumber, (default:1)
         * @param {number} [pagesize] Elements per Page, (default:10)
         * @param {string} [type] Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, possible values: BITMASK: 1 &#x3D; Wellness, 2 &#x3D; Winter, 4 &#x3D; Summer, 8 &#x3D; Culture, 16 &#x3D; Other, 32 &#x3D; Gastronomy, 64 &#x3D; Mobility, 128 &#x3D; Shops and Services), (default: 255 &#x3D;&#x3D; ALL), REFERENCE TO: GET /v1/ODHActivityPoiTypes
         * @param {string} [subtype] Subtype of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype reference to ODHActivityPoiTypes)
         * @param {string} [poitype] Additional Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype, SubType reference to ODHActivityPoiTypes)
         * @param {string} [idlist] IDFilter (Separator &#x27;,&#x27; List of ODHActivityPoi IDs), (default:&#x27;null&#x27;)
         * @param {string} [locfilter] Locfilter (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), mun + MUNICIPALITYID &#x3D; (Filter by Municipality), fra + FRACTIONID &#x3D; (Filter by Fraction), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
         * @param {string} [langfilter] ODHActivityPoi Langfilter (returns only SmgPois available in the selected Language, Separator &#x27;,&#x27; possible values: &#x27;de,it,en,nl,sc,pl,fr,ru&#x27;, &#x27;null&#x27;: Filter disabled)
         * @param {string} [areafilter] AreaFilter (Alternate Locfilter, can be combined with locfilter) (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), skr + SKIREGIONID &#x3D; (Filter by Skiregion), ska + SKIAREAID &#x3D; (Filter by Skiarea), are + AREAID &#x3D; (Filter by LTS Area), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
         * @param {boolean} [highlight] Hightlight Filter (possible values: &#x27;false&#x27; &#x3D; only ODHActivityPoi with Highlight false, &#x27;true&#x27; &#x3D; only ODHActivityPoi with Highlight true), (default:&#x27;null&#x27;)
         * @param {string} [source] Source Filter (possible Values: &#x27;null&#x27; Displays all ODHActivityPoi, &#x27;None&#x27;, &#x27;ActivityData&#x27;, &#x27;PoiData&#x27;, &#x27;GastronomicData&#x27;, &#x27;MuseumData&#x27;, &#x27;Magnolia&#x27;, &#x27;Content&#x27;, &#x27;SuedtirolWein&#x27;, &#x27;ArchApp&#x27; (default:&#x27;null&#x27;)
         * @param {string} [odhtagfilter] ODH Taglist Filter (refers to Array SmgTags) (String, Separator &#x27;,&#x27; more Tags possible, available Tags reference to &#x27;api/ODHTag?validforentity&#x3D;smgpoi&#x27;), (default:&#x27;null&#x27;)
         * @param {boolean} [odhactive] ODH Active (Published) ODHActivityPoi Filter (Refers to field SmgActive) (possible Values: &#x27;true&#x27; only published ODHActivityPoi, &#x27;false&#x27; only not published ODHActivityPoi, (default:&#x27;null&#x27;)
         * @param {boolean} [active] Active ODHActivityPoi Filter (possible Values: &#x27;true&#x27; only active ODHActivityPoi, &#x27;false&#x27; only not active ODHActivityPoi, (default:&#x27;null&#x27;)
         * @param {string} [seed] Seed &#x27;1 - 10&#x27; for Random Sorting, &#x27;0&#x27; generates a Random Seed, not provided disables Random Sorting, (default:&#x27;null&#x27;)
         * @param {string} [latitude] GeoFilter Latitude Format: &#x27;46.624975&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
         * @param {string} [longitude] GeoFilter Longitude Format: &#x27;11.369909&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
         * @param {string} [radius] Radius to Search in Meters. Only Object withhin the given point and radius are returned and sorted by distance. Random Sorting is disabled if the GeoFilter Informations are provided, (default:&#x27;null&#x27;)
         * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
         * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
         * @param {string} [updatefrom] Date from Format (yyyy-MM-dd) (all GBActivityPoi with LastChange &amp;gt;&#x3D; datefrom are passed), (default: null)
         * @param {string} [searchfilter] String to search for, Title in all languages are searched, (default: null)
         * @param {string} [rawfilter] Rawfilter to pass, (default: null)          
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetODHActivityPoiList: async (pagenumber?: number, pagesize?: number, type?: string, subtype?: string, poitype?: string, idlist?: string, locfilter?: string, langfilter?: string, areafilter?: string, highlight?: boolean, source?: string, odhtagfilter?: string, odhactive?: boolean, active?: boolean, seed?: string, latitude?: string, longitude?: string, radius?: string, fields?: string, language?: string, hasimage?: boolean, updatefrom?: string, searchfilter?: string, rawfilter?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ODHActivityPoi`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth2", [""])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (pagenumber !== undefined) {
                localVarQueryParameter['pagenumber'] = pagenumber;
            }

            if (pagesize !== undefined) {
                localVarQueryParameter['pagesize'] = pagesize;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (subtype !== undefined) {
                localVarQueryParameter['subtype'] = subtype;
            }

            if (poitype !== undefined) {
                localVarQueryParameter['poitype'] = poitype;
            }

            if (idlist !== undefined) {
                localVarQueryParameter['idlist'] = idlist;
            }

            if (locfilter !== undefined) {
                localVarQueryParameter['locfilter'] = locfilter;
            }

            if (langfilter !== undefined) {
                localVarQueryParameter['langfilter'] = langfilter;
            }

            if (areafilter !== undefined) {
                localVarQueryParameter['areafilter'] = areafilter;
            }

            if (highlight !== undefined) {
                localVarQueryParameter['highlight'] = highlight;
            }

            if (source !== undefined) {
                localVarQueryParameter['source'] = source;
            }

            if (odhtagfilter !== undefined) {
                localVarQueryParameter['odhtagfilter'] = odhtagfilter;
            }

            if (odhactive !== undefined) {
                localVarQueryParameter['odhactive'] = odhactive;
            }

            if (active !== undefined) {
                localVarQueryParameter['active'] = active;
            }

            if (seed !== undefined) {
                localVarQueryParameter['seed'] = seed;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            if (radius !== undefined) {
                localVarQueryParameter['radius'] = radius;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (hasimage !== undefined) {
                localVarQueryParameter['hasimage'] = hasimage;
            }

            if (updatefrom !== undefined) {
                localVarQueryParameter['updatefrom'] = updatefrom;
            }

            if (searchfilter !== undefined) {
                localVarQueryParameter['searchfilter'] = searchfilter;
            }

            if (rawfilter !== undefined) {
                localVarQueryParameter['rawfilter'] = rawfilter;
            }

            localVarQueryParameter['origin'] = "webcomp-tourism-detail";

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },     
        /**
         * 
         * @summary GET ODHActivityPoi Single
         * @param {string} id ID of the Poi
         * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
         * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetODHActivityPoiSingle: async (id: string, fields?: string, language?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling oDHActivityPoiGetODHActivityPoiSingle.');
            }
            const localVarPath = `/v1/ODHActivityPoi/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth2", [""])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            localVarQueryParameter['origin'] = "webcomp-tourism-detail";


            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },     
    }
};

/**
 * ODHActivityPoiApi - functional programming interface
 * @export
 */
export const ODHActivityPoiApiFp = function(configuration?: Configuration) {
    return {      
        /**
         * 
         * @summary GET ODHActivityPoi Types List
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oDHActivityPoiGetAllODHActivityPoiTypesList(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SmgPoiTypes>>> {
            const localVarAxiosArgs = await ODHActivityPoiApiAxiosParamCreator(configuration).oDHActivityPoiGetAllODHActivityPoiTypesList(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary GET ODHActivityPoi Types Single
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oDHActivityPoiGetAllODHActivityPoiTypesSingle(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SmgPoiTypes>> {
            const localVarAxiosArgs = await ODHActivityPoiApiAxiosParamCreator(configuration).oDHActivityPoiGetAllODHActivityPoiTypesSingle(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary GET ODHActivityPoi List
         * @param {number} [pagenumber] Pagenumber, (default:1)
         * @param {number} [pagesize] Elements per Page, (default:10)
         * @param {string} [type] Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, possible values: BITMASK: 1 &#x3D; Wellness, 2 &#x3D; Winter, 4 &#x3D; Summer, 8 &#x3D; Culture, 16 &#x3D; Other, 32 &#x3D; Gastronomy, 64 &#x3D; Mobility, 128 &#x3D; Shops and Services), (default: 255 &#x3D;&#x3D; ALL), REFERENCE TO: GET /v1/ODHActivityPoiTypes
         * @param {string} [subtype] Subtype of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype reference to ODHActivityPoiTypes)
         * @param {string} [poitype] Additional Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype, SubType reference to ODHActivityPoiTypes)
         * @param {string} [idlist] IDFilter (Separator &#x27;,&#x27; List of ODHActivityPoi IDs), (default:&#x27;null&#x27;)
         * @param {string} [locfilter] Locfilter (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), mun + MUNICIPALITYID &#x3D; (Filter by Municipality), fra + FRACTIONID &#x3D; (Filter by Fraction), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
         * @param {string} [langfilter] ODHActivityPoi Langfilter (returns only SmgPois available in the selected Language, Separator &#x27;,&#x27; possible values: &#x27;de,it,en,nl,sc,pl,fr,ru&#x27;, &#x27;null&#x27;: Filter disabled)
         * @param {string} [areafilter] AreaFilter (Alternate Locfilter, can be combined with locfilter) (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), skr + SKIREGIONID &#x3D; (Filter by Skiregion), ska + SKIAREAID &#x3D; (Filter by Skiarea), are + AREAID &#x3D; (Filter by LTS Area), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
         * @param {boolean} [highlight] Hightlight Filter (possible values: &#x27;false&#x27; &#x3D; only ODHActivityPoi with Highlight false, &#x27;true&#x27; &#x3D; only ODHActivityPoi with Highlight true), (default:&#x27;null&#x27;)
         * @param {string} [source] Source Filter (possible Values: &#x27;null&#x27; Displays all ODHActivityPoi, &#x27;None&#x27;, &#x27;ActivityData&#x27;, &#x27;PoiData&#x27;, &#x27;GastronomicData&#x27;, &#x27;MuseumData&#x27;, &#x27;Magnolia&#x27;, &#x27;Content&#x27;, &#x27;SuedtirolWein&#x27;, &#x27;ArchApp&#x27; (default:&#x27;null&#x27;)
         * @param {string} [odhtagfilter] ODH Taglist Filter (refers to Array SmgTags) (String, Separator &#x27;,&#x27; more Tags possible, available Tags reference to &#x27;api/ODHTag?validforentity&#x3D;smgpoi&#x27;), (default:&#x27;null&#x27;)
         * @param {boolean} [odhactive] ODH Active (Published) ODHActivityPoi Filter (Refers to field SmgActive) (possible Values: &#x27;true&#x27; only published ODHActivityPoi, &#x27;false&#x27; only not published ODHActivityPoi, (default:&#x27;null&#x27;)
         * @param {boolean} [active] Active ODHActivityPoi Filter (possible Values: &#x27;true&#x27; only active ODHActivityPoi, &#x27;false&#x27; only not active ODHActivityPoi, (default:&#x27;null&#x27;)
         * @param {string} [seed] Seed &#x27;1 - 10&#x27; for Random Sorting, &#x27;0&#x27; generates a Random Seed, not provided disables Random Sorting, (default:&#x27;null&#x27;)
         * @param {string} [latitude] GeoFilter Latitude Format: &#x27;46.624975&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
         * @param {string} [longitude] GeoFilter Longitude Format: &#x27;11.369909&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
         * @param {string} [radius] Radius to Search in Meters. Only Object withhin the given point and radius are returned and sorted by distance. Random Sorting is disabled if the GeoFilter Informations are provided, (default:&#x27;null&#x27;)
         * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
         * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
         * @param {string} [updatefrom] Date from Format (yyyy-MM-dd) (all GBActivityPoi with LastChange &amp;gt;&#x3D; datefrom are passed), (default: null)
         * @param {string} [searchfilter] String to search for, Title in all languages are searched, (default: null)
         * @param {string} [rawfilter] rawfilter to pass, (default: null)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oDHActivityPoiGetODHActivityPoiList(pagenumber?: number, pagesize?: number, type?: string, subtype?: string, poitype?: string, idlist?: string, locfilter?: string, langfilter?: string, areafilter?: string, highlight?: boolean, source?: string, odhtagfilter?: string, odhactive?: boolean, active?: boolean, seed?: string, latitude?: string, longitude?: string, radius?: string, fields?: string, language?: string, hasimage?: boolean, updatefrom?: string, searchfilter?: string, rawfilter?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ODHActivityPoi>>> {
            const localVarAxiosArgs = await ODHActivityPoiApiAxiosParamCreator(configuration).oDHActivityPoiGetODHActivityPoiList(pagenumber, pagesize, type, subtype, poitype, idlist, locfilter, langfilter, areafilter, highlight, source, odhtagfilter, odhactive, active, seed, latitude, longitude, radius, fields, language, hasimage, updatefrom, searchfilter, rawfilter, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary GET ODHActivityPoi Single
         * @param {string} id ID of the Poi
         * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
         * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oDHActivityPoiGetODHActivityPoiSingle(id: string, fields?: string, language?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ODHActivityPoi>> {
            const localVarAxiosArgs = await ODHActivityPoiApiAxiosParamCreator(configuration).oDHActivityPoiGetODHActivityPoiSingle(id, fields, language, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },     
    }
};

/**
 * ODHActivityPoiApi - factory interface
 * @export
 */
export const ODHActivityPoiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary GET ODHActivityPoi Types List
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetAllODHActivityPoiTypesList(options?: any): AxiosPromise<Array<SmgPoiTypes>> {
            return ODHActivityPoiApiFp(configuration).oDHActivityPoiGetAllODHActivityPoiTypesList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET ODHActivityPoi Types Single
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetAllODHActivityPoiTypesSingle(id: string, options?: any): AxiosPromise<SmgPoiTypes> {
            return ODHActivityPoiApiFp(configuration).oDHActivityPoiGetAllODHActivityPoiTypesSingle(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET ODHActivityPoi List
         * @param {number} [pagenumber] Pagenumber, (default:1)
         * @param {number} [pagesize] Elements per Page, (default:10)
         * @param {string} [type] Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, possible values: BITMASK: 1 &#x3D; Wellness, 2 &#x3D; Winter, 4 &#x3D; Summer, 8 &#x3D; Culture, 16 &#x3D; Other, 32 &#x3D; Gastronomy, 64 &#x3D; Mobility, 128 &#x3D; Shops and Services), (default: 255 &#x3D;&#x3D; ALL), REFERENCE TO: GET /v1/ODHActivityPoiTypes
         * @param {string} [subtype] Subtype of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype reference to ODHActivityPoiTypes)
         * @param {string} [poitype] Additional Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype, SubType reference to ODHActivityPoiTypes)
         * @param {string} [idlist] IDFilter (Separator &#x27;,&#x27; List of ODHActivityPoi IDs), (default:&#x27;null&#x27;)
         * @param {string} [locfilter] Locfilter (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), mun + MUNICIPALITYID &#x3D; (Filter by Municipality), fra + FRACTIONID &#x3D; (Filter by Fraction), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
         * @param {string} [langfilter] ODHActivityPoi Langfilter (returns only SmgPois available in the selected Language, Separator &#x27;,&#x27; possible values: &#x27;de,it,en,nl,sc,pl,fr,ru&#x27;, &#x27;null&#x27;: Filter disabled)
         * @param {string} [areafilter] AreaFilter (Alternate Locfilter, can be combined with locfilter) (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), skr + SKIREGIONID &#x3D; (Filter by Skiregion), ska + SKIAREAID &#x3D; (Filter by Skiarea), are + AREAID &#x3D; (Filter by LTS Area), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
         * @param {boolean} [highlight] Hightlight Filter (possible values: &#x27;false&#x27; &#x3D; only ODHActivityPoi with Highlight false, &#x27;true&#x27; &#x3D; only ODHActivityPoi with Highlight true), (default:&#x27;null&#x27;)
         * @param {string} [source] Source Filter (possible Values: &#x27;null&#x27; Displays all ODHActivityPoi, &#x27;None&#x27;, &#x27;ActivityData&#x27;, &#x27;PoiData&#x27;, &#x27;GastronomicData&#x27;, &#x27;MuseumData&#x27;, &#x27;Magnolia&#x27;, &#x27;Content&#x27;, &#x27;SuedtirolWein&#x27;, &#x27;ArchApp&#x27; (default:&#x27;null&#x27;)
         * @param {string} [odhtagfilter] ODH Taglist Filter (refers to Array SmgTags) (String, Separator &#x27;,&#x27; more Tags possible, available Tags reference to &#x27;api/ODHTag?validforentity&#x3D;smgpoi&#x27;), (default:&#x27;null&#x27;)
         * @param {boolean} [odhactive] ODH Active (Published) ODHActivityPoi Filter (Refers to field SmgActive) (possible Values: &#x27;true&#x27; only published ODHActivityPoi, &#x27;false&#x27; only not published ODHActivityPoi, (default:&#x27;null&#x27;)
         * @param {boolean} [active] Active ODHActivityPoi Filter (possible Values: &#x27;true&#x27; only active ODHActivityPoi, &#x27;false&#x27; only not active ODHActivityPoi, (default:&#x27;null&#x27;)
         * @param {string} [seed] Seed &#x27;1 - 10&#x27; for Random Sorting, &#x27;0&#x27; generates a Random Seed, not provided disables Random Sorting, (default:&#x27;null&#x27;)
         * @param {string} [latitude] GeoFilter Latitude Format: &#x27;46.624975&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
         * @param {string} [longitude] GeoFilter Longitude Format: &#x27;11.369909&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
         * @param {string} [radius] Radius to Search in Meters. Only Object withhin the given point and radius are returned and sorted by distance. Random Sorting is disabled if the GeoFilter Informations are provided, (default:&#x27;null&#x27;)
         * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
         * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
         * @param {string} [updatefrom] Date from Format (yyyy-MM-dd) (all GBActivityPoi with LastChange &amp;gt;&#x3D; datefrom are passed), (default: null)
         * @param {string} [searchfilter] String to search for, Title in all languages are searched, (default: null)
         * @param {string} [rawfilter] rawfilter to pass, (default: null)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetODHActivityPoiList(pagenumber?: number, pagesize?: number, type?: string, subtype?: string, poitype?: string, idlist?: string, locfilter?: string, langfilter?: string, areafilter?: string, highlight?: boolean, source?: string, odhtagfilter?: string, odhactive?: boolean, active?: boolean, seed?: string, latitude?: string, longitude?: string, radius?: string, fields?: string, language?: string, hasimage?: boolean, updatefrom?: string, searchfilter?: string, rawfilter?: string, options?: any): AxiosPromise<Array<ODHActivityPoi>> {
            return ODHActivityPoiApiFp(configuration).oDHActivityPoiGetODHActivityPoiList(pagenumber, pagesize, type, subtype, poitype, idlist, locfilter, langfilter, areafilter, highlight, source, odhtagfilter, odhactive, active, seed, latitude, longitude, radius, fields, language, hasimage, updatefrom, searchfilter, rawfilter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET ODHActivityPoi Single
         * @param {string} id ID of the Poi
         * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
         * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oDHActivityPoiGetODHActivityPoiSingle(id: string, fields?: string, language?: string, options?: any): AxiosPromise<ODHActivityPoi> {
            return ODHActivityPoiApiFp(configuration).oDHActivityPoiGetODHActivityPoiSingle(id, fields, language, options).then((request) => request(axios, basePath));
        },      
    };
};

/**
 * ODHActivityPoiApi - object-oriented interface
 * @export
 * @class ODHActivityPoiApi
 * @extends {BaseAPI}
 */
export class ODHActivityPoiApi extends BaseAPI {
    /**
     * 
     * @summary GET ODHActivityPoi Types List
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ODHActivityPoiApi
     */
    public oDHActivityPoiGetAllODHActivityPoiTypesList(options?: any) {
        return ODHActivityPoiApiFp(this.configuration).oDHActivityPoiGetAllODHActivityPoiTypesList(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary GET ODHActivityPoi Types Single
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ODHActivityPoiApi
     */
    public oDHActivityPoiGetAllODHActivityPoiTypesSingle(id: string, options?: any) {
        return ODHActivityPoiApiFp(this.configuration).oDHActivityPoiGetAllODHActivityPoiTypesSingle(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary GET ODHActivityPoi List
     * @param {number} [pagenumber] Pagenumber, (default:1)
     * @param {number} [pagesize] Elements per Page, (default:10)
     * @param {string} [type] Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, possible values: BITMASK: 1 &#x3D; Wellness, 2 &#x3D; Winter, 4 &#x3D; Summer, 8 &#x3D; Culture, 16 &#x3D; Other, 32 &#x3D; Gastronomy, 64 &#x3D; Mobility, 128 &#x3D; Shops and Services), (default: 255 &#x3D;&#x3D; ALL), REFERENCE TO: GET /v1/ODHActivityPoiTypes
     * @param {string} [subtype] Subtype of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype reference to ODHActivityPoiTypes)
     * @param {string} [poitype] Additional Type of the ODHActivityPoi (&#x27;null&#x27; &#x3D; Filter disabled, BITMASK Filter, available SubTypes depends on the selected Maintype, SubType reference to ODHActivityPoiTypes)
     * @param {string} [idlist] IDFilter (Separator &#x27;,&#x27; List of ODHActivityPoi IDs), (default:&#x27;null&#x27;)
     * @param {string} [locfilter] Locfilter (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), mun + MUNICIPALITYID &#x3D; (Filter by Municipality), fra + FRACTIONID &#x3D; (Filter by Fraction), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
     * @param {string} [langfilter] ODHActivityPoi Langfilter (returns only SmgPois available in the selected Language, Separator &#x27;,&#x27; possible values: &#x27;de,it,en,nl,sc,pl,fr,ru&#x27;, &#x27;null&#x27;: Filter disabled)
     * @param {string} [areafilter] AreaFilter (Alternate Locfilter, can be combined with locfilter) (Separator &#x27;,&#x27; possible values: reg + REGIONID &#x3D; (Filter by Region), tvs + TOURISMASSOCIATIONID &#x3D; (Filter by Tourismassociation), skr + SKIREGIONID &#x3D; (Filter by Skiregion), ska + SKIAREAID &#x3D; (Filter by Skiarea), are + AREAID &#x3D; (Filter by LTS Area), &#x27;null&#x27; &#x3D; No Filter), (default:&#x27;null&#x27;)
     * @param {boolean} [highlight] Hightlight Filter (possible values: &#x27;false&#x27; &#x3D; only ODHActivityPoi with Highlight false, &#x27;true&#x27; &#x3D; only ODHActivityPoi with Highlight true), (default:&#x27;null&#x27;)
     * @param {string} [source] Source Filter (possible Values: &#x27;null&#x27; Displays all ODHActivityPoi, &#x27;None&#x27;, &#x27;ActivityData&#x27;, &#x27;PoiData&#x27;, &#x27;GastronomicData&#x27;, &#x27;MuseumData&#x27;, &#x27;Magnolia&#x27;, &#x27;Content&#x27;, &#x27;SuedtirolWein&#x27;, &#x27;ArchApp&#x27; (default:&#x27;null&#x27;)
     * @param {string} [odhtagfilter] ODH Taglist Filter (refers to Array SmgTags) (String, Separator &#x27;,&#x27; more Tags possible, available Tags reference to &#x27;api/ODHTag?validforentity&#x3D;smgpoi&#x27;), (default:&#x27;null&#x27;)
     * @param {boolean} [odhactive] ODH Active (Published) ODHActivityPoi Filter (Refers to field SmgActive) (possible Values: &#x27;true&#x27; only published ODHActivityPoi, &#x27;false&#x27; only not published ODHActivityPoi, (default:&#x27;null&#x27;)
     * @param {boolean} [active] Active ODHActivityPoi Filter (possible Values: &#x27;true&#x27; only active ODHActivityPoi, &#x27;false&#x27; only not active ODHActivityPoi, (default:&#x27;null&#x27;)
     * @param {string} [seed] Seed &#x27;1 - 10&#x27; for Random Sorting, &#x27;0&#x27; generates a Random Seed, not provided disables Random Sorting, (default:&#x27;null&#x27;)
     * @param {string} [latitude] GeoFilter Latitude Format: &#x27;46.624975&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
     * @param {string} [longitude] GeoFilter Longitude Format: &#x27;11.369909&#x27;, &#x27;null&#x27; &#x3D; disabled, (default:&#x27;null&#x27;)
     * @param {string} [radius] Radius to Search in Meters. Only Object withhin the given point and radius are returned and sorted by distance. Random Sorting is disabled if the GeoFilter Informations are provided, (default:&#x27;null&#x27;)
     * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
     * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
     * @param {boolean} [hasimage] 
     * @param {string} [updatefrom] Date from Format (yyyy-MM-dd) (all GBActivityPoi with LastChange &amp;gt;&#x3D; datefrom are passed), (default: null)
     * @param {string} [searchfilter] String to search for, Title in all languages are searched, (default: null)
     * @param {string} [rawfilter] rawfilter to pass, (default: null)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ODHActivityPoiApi
     */
    public oDHActivityPoiGetODHActivityPoiList(pagenumber?: number, pagesize?: number, type?: string, subtype?: string, poitype?: string, idlist?: string, locfilter?: string, langfilter?: string, areafilter?: string, highlight?: boolean, source?: string, odhtagfilter?: string, odhactive?: boolean, active?: boolean, seed?: string, latitude?: string, longitude?: string, radius?: string, fields?: string, language?: string, hasimage?: boolean, updatefrom?: string, searchfilter?: string, rawfilter?: string, options?: any) {
        return ODHActivityPoiApiFp(this.configuration).oDHActivityPoiGetODHActivityPoiList(pagenumber, pagesize, type, subtype, poitype, idlist, locfilter, langfilter, areafilter, highlight, source, odhtagfilter, odhactive, active, seed, latitude, longitude, radius, fields, language, hasimage, updatefrom, searchfilter, rawfilter, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary GET ODHActivityPoi Single
     * @param {string} id ID of the Poi
     * @param {string} [fields] Select fields to display, More fields are indicated by separator &#x27;,&#x27; example fields&#x3D;Id,Active,Shortname. Select also Dictionary fields, example Detail.de.Title, or Elements of Arrays example ImageGallery[0].ImageUrl. (default:&#x27;null&#x27; all fields are displayed)
     * @param {string} [language] Language field selector, displays data and fields available in the selected language (default:&#x27;null&#x27; all languages are displayed)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ODHActivityPoiApi
     */
    public oDHActivityPoiGetODHActivityPoiSingle(id: string, fields?: string, language?: string, options?: any) {
        return ODHActivityPoiApiFp(this.configuration).oDHActivityPoiGetODHActivityPoiSingle(id, fields, language, options).then((request) => request(this.axios, this.basePath));
    }   
}