/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/accommodation-api';
export * from './apis/activity-api';
export * from './apis/article-api';
export * from './apis/common-api';
export * from './apis/event-api';
export * from './apis/gastronomy-api';
export * from './apis/json-ldapi';
export * from './apis/location-api';
export * from './apis/login-api';
export * from './apis/odhactivity-poi-api';
export * from './apis/odhtag-api';
export * from './apis/poi-api';
export * from './apis/venue-api';
export * from './apis/weather-api';
export * from './apis/webcam-info-api';

