/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccoFeatures
 */
export interface AccoFeatures {
    /**
     * 
     * @type {string}
     * @memberof AccoFeatures
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoFeatures
     */
    bitmask?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoFeatures
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoFeatures
     */
    key?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof AccoFeatures
     */
    typeDesc?: any;
}
