/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccoRoom
 */
export interface AccoRoom {
    /**
     * 
     * @type {LicenseInfo}
     * @memberof AccoRoom
     */
    licenseInfo?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    shortname?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    a0RID?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    roomtype?: any;
    /**
     * 
     * @type {Array&lt;AccoFeature&gt;}
     * @memberof AccoRoom
     */
    features?: any;
    /**
     * 
     * @type {{ [key, string]: AccoRoomDetail;}}
     * @memberof AccoRoom
     */
    accoRoomDetail?: any;
    /**
     * 
     * @type {Array&lt;ImageGallery&gt;}
     * @memberof AccoRoom
     */
    imageGallery?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccoRoom
     */
    hasLanguage?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    lTSId?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    hGVId?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    source?: any;
    /**
     * 
     * @type {string}
     * @memberof AccoRoom
     */
    roomCode?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoRoom
     */
    roommax?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoRoom
     */
    roommin?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoRoom
     */
    roomstd?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoRoom
     */
    priceFrom?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoRoom
     */
    roomQuantity?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccoRoom
     */
    roomNumbers?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoRoom
     */
    roomClassificationCodes?: any;
    /**
     * 
     * @type {number}
     * @memberof AccoRoom
     */
    roomtypeInt?: any;
    /**
     * 
     * @type {Date}
     * @memberof AccoRoom
     */
    lastChange?: any;
}
