/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccommodationLocalized
 */
export interface AccommodationLocalized {
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    hgvId?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    shortname?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    units?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    beds?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLocalized
     */
    hasApartment?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLocalized
     */
    hasRoom?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLocalized
     */
    isBookable?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLocalized
     */
    smgActive?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLocalized
     */
    tVMember?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    tourismVereinId?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    mainLanguage?: any;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationLocalized
     */
    firstImport?: any;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationLocalized
     */
    lastChange?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    gpstype?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    latitude?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    longitude?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    altitude?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    altitudeUnitofMeasure?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    accoCategoryId?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    accoTypeId?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    districtId?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccommodationLocalized
     */
    boardIds?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccommodationLocalized
     */
    badgeIds?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccommodationLocalized
     */
    themeIds?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccommodationLocalized
     */
    specialFeaturesIds?: any;
    /**
     * 
     * @type {AccoDetail}
     * @memberof AccommodationLocalized
     */
    accoDetail?: any;
    /**
     * 
     * @type {Array&lt;AccoBookingChannel&gt;}
     * @memberof AccommodationLocalized
     */
    accoBookingChannel?: any;
    /**
     * 
     * @type {Array&lt;ImageGalleryLocalized&gt;}
     * @memberof AccommodationLocalized
     */
    imageGallery?: any;
    /**
     * 
     * @type {LocationInfoLocalized}
     * @memberof AccommodationLocalized
     */
    locationInfo?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    gastronomyId?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccommodationLocalized
     */
    smgTags?: any;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLocalized
     */
    trustYouID?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    trustYouScore?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    trustYouResults?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLocalized
     */
    trustYouActive?: any;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLocalized
     */
    trustYouState?: any;
    /**
     * 
     * @type {Array&lt;MssResponseShort&gt;}
     * @memberof AccommodationLocalized
     */
    mssResponseShort?: any;
}
