/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdditionalContact
 */
export interface AdditionalContact {
    /**
     * 
     * @type {string}
     * @memberof AdditionalContact
     */
    type?: any;
    /**
     * 
     * @type {ContactInfos}
     * @memberof AdditionalContact
     */
    contactInfos?: any;
    /**
     * 
     * @type {string}
     * @memberof AdditionalContact
     */
    description?: any;
}
