/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * 
     * @type {LicenseInfo}
     * @memberof Article
     */
    licenseInfo?: any;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Article
     */
    active?: any;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    shortname?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Article
     */
    highlight?: any;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    subType?: any;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    firstImport?: any;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    lastChange?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Article
     */
    smgActive?: any;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    articleDate?: any;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    articleDateTo?: any;
    /**
     * 
     * @type {Array&lt;OperationSchedule&gt;}
     * @memberof Article
     */
    operationSchedule?: any;
    /**
     * 
     * @type {Array&lt;GpsInfo&gt;}
     * @memberof Article
     */
    gpsInfo?: any;
    /**
     * 
     * @type {Array&lt;GpsTrack&gt;}
     * @memberof Article
     */
    gpsTrack?: any;
    /**
     * 
     * @type {Array&lt;ImageGallery&gt;}
     * @memberof Article
     */
    imageGallery?: any;
    /**
     * 
     * @type {{ [key, string]: Detail;}}
     * @memberof Article
     */
    detail?: any;
    /**
     * 
     * @type {{ [key, string]: ContactInfos;}}
     * @memberof Article
     */
    contactInfos?: any;
    /**
     * 
     * @type {{ [key, string]: AdditionalArticleInfos;}}
     * @memberof Article
     */
    additionalArticleInfos?: any;
    /**
     * 
     * @type {{ [key, string]: ArticleLinkInfo;}}
     * @memberof Article
     */
    articleLinkInfo?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Article
     */
    smgTags?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Article
     */
    hasLanguage?: any;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    customId?: any;
}
