/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BezirksForecast
 */
export interface BezirksForecast {
    /**
     * 
     * @type {Date}
     * @memberof BezirksForecast
     */
    date?: any;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    weatherCode?: any;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    weatherDesc?: any;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    weatherImgUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    maxTemp?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    minTemp?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    freeze?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    rainFrom?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    rainTo?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part1?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part2?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part3?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part4?: any;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    thunderstorm?: any;
}
