/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BezirksWeather
 */
export interface BezirksWeather {
    /**
     * 
     * @type {number}
     * @memberof BezirksWeather
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof BezirksWeather
     */
    districtName?: any;
    /**
     * 
     * @type {Date}
     * @memberof BezirksWeather
     */
    date?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BezirksWeather
     */
    tourismVereinIds?: any;
    /**
     * 
     * @type {Array&lt;BezirksForecast&gt;}
     * @memberof BezirksWeather
     */
    bezirksForecast?: any;
}
