/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body
 */
export interface Body {
    /**
     * use 'password' for login operation
     * @type {string}
     * @memberof Body
     */
    grantType: any;
    /**
     * 
     * @type {string}
     * @memberof Body
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof Body
     */
    password?: any;
}
