/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DDAttributesMultimedia
 */
export interface DDAttributesMultimedia {
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributesMultimedia
     */
    _abstract?: any;
    /**
     * 
     * @type {string}
     * @memberof DDAttributesMultimedia
     */
    contentType?: any;
    /**
     * 
     * @type {string}
     * @memberof DDAttributesMultimedia
     */
    url?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof DDAttributesMultimedia
     */
    categories?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributesMultimedia
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof DDAttributesMultimedia
     */
    duration?: any;
    /**
     * 
     * @type {number}
     * @memberof DDAttributesMultimedia
     */
    height?: any;
    /**
     * 
     * @type {string}
     * @memberof DDAttributesMultimedia
     */
    license?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributesMultimedia
     */
    name?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributesMultimedia
     */
    shortName?: any;
    /**
     * 
     * @type {number}
     * @memberof DDAttributesMultimedia
     */
    width?: any;
}
