/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DDAttributes
 */
export interface DDAttributes {
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributes
     */
    _abstract?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof DDAttributes
     */
    categories?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributes
     */
    description?: any;
    /**
     * 
     * @type {Array&lt;DDGeometry&gt;}
     * @memberof DDAttributes
     */
    geometries?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributes
     */
    howToArrive?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributes
     */
    name?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributes
     */
    shortName?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof DDAttributes
     */
    url?: any;
    /**
     * 
     * @type {Array&lt;DDAddress&gt;}
     * @memberof DDAttributes
     */
    address?: any;
    /**
     * 
     * @type {DDOpeninghours}
     * @memberof DDAttributes
     */
    openingHours?: any;
    /**
     * 
     * @type {number}
     * @memberof DDAttributes
     */
    beds?: any;
}
