/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DDDimension
 */
export interface DDDimension {
    /**
     * 
     * @type {number}
     * @memberof DDDimension
     */
    squareMeters?: any;
    /**
     * 
     * @type {number}
     * @memberof DDDimension
     */
    doorHeight?: any;
    /**
     * 
     * @type {number}
     * @memberof DDDimension
     */
    doorWidth?: any;
    /**
     * 
     * @type {number}
     * @memberof DDDimension
     */
    height?: any;
    /**
     * 
     * @type {number}
     * @memberof DDDimension
     */
    length?: any;
    /**
     * 
     * @type {number}
     * @memberof DDDimension
     */
    width?: any;
}
