/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DDOpeninghours
 */
export interface DDOpeninghours {
    /**
     * 
     * @type {Array&lt;DDOpeninghoursweekly&gt;}
     * @memberof DDOpeninghours
     */
    weeklySchedules?: any;
    /**
     * 
     * @type {{ [key, string]: Array&lt;DDOpeningTimes&gt;;}}
     * @memberof DDOpeninghours
     */
    dailySchedules?: any;
}
