/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventPrice
 */
export interface EventPrice {
    /**
     * 
     * @type {number}
     * @memberof EventPrice
     */
    price?: any;
    /**
     * 
     * @type {string}
     * @memberof EventPrice
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof EventPrice
     */
    pstd?: any;
    /**
     * 
     * @type {string}
     * @memberof EventPrice
     */
    shortDesc?: any;
    /**
     * 
     * @type {string}
     * @memberof EventPrice
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof EventPrice
     */
    language?: any;
}
