/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExperienceAreaLocalized
 */
export interface ExperienceAreaLocalized {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ExperienceAreaLocalized
     */
    districtIds?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ExperienceAreaLocalized
     */
    tourismvereinIds?: any;
    /**
     * 
     * @type {Array&lt;GpsPolygon&gt;}
     * @memberof ExperienceAreaLocalized
     */
    gpsPolygon?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ExperienceAreaLocalized
     */
    visibleInSearch?: any;
    /**
     * 
     * @type {string}
     * @memberof ExperienceAreaLocalized
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ExperienceAreaLocalized
     */
    active?: any;
    /**
     * 
     * @type {string}
     * @memberof ExperienceAreaLocalized
     */
    customId?: any;
    /**
     * 
     * @type {string}
     * @memberof ExperienceAreaLocalized
     */
    shortname?: any;
    /**
     * 
     * @type {string}
     * @memberof ExperienceAreaLocalized
     */
    gpstype?: any;
    /**
     * 
     * @type {number}
     * @memberof ExperienceAreaLocalized
     */
    latitude?: any;
    /**
     * 
     * @type {number}
     * @memberof ExperienceAreaLocalized
     */
    longitude?: any;
    /**
     * 
     * @type {number}
     * @memberof ExperienceAreaLocalized
     */
    altitude?: any;
    /**
     * 
     * @type {string}
     * @memberof ExperienceAreaLocalized
     */
    altitudeUnitofMeasure?: any;
    /**
     * 
     * @type {Detail}
     * @memberof ExperienceAreaLocalized
     */
    detail?: any;
    /**
     * 
     * @type {ContactInfos}
     * @memberof ExperienceAreaLocalized
     */
    contactInfos?: any;
    /**
     * 
     * @type {Array&lt;ImageGalleryLocalized&gt;}
     * @memberof ExperienceAreaLocalized
     */
    imageGallery?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ExperienceAreaLocalized
     */
    smgTags?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ExperienceAreaLocalized
     */
    smgActive?: any;
}
