/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExperienceAreaName
 */
export interface ExperienceAreaName {
    /**
     * 
     * @type {string}
     * @memberof ExperienceAreaName
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof ExperienceAreaName
     */
    name?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ExperienceAreaName
     */
    districtIds?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ExperienceAreaName
     */
    tourismvereinIds?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ExperienceAreaName
     */
    visibleInSearch?: any;
}
