/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Forecast
 */
export interface Forecast {
    /**
     * 
     * @type {Date}
     * @memberof Forecast
     */
    date?: any;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    tempMaxmax?: any;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    tempMaxmin?: any;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    tempMinmax?: any;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    tempMinmin?: any;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    weatherdesc?: any;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    weathercode?: any;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    weatherImgurl?: any;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    reliability?: any;
}
