/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GBLTSActivityPoiLocalized
 */
export interface GBLTSActivityPoiLocalized {
    /**
     * 
     * @type {{ [key, string]: GpsInfo;}}
     * @memberof GBLTSActivityPoiLocalized
     */
    gpsPoints?: any;
    /**
     * 
     * @type {Array&lt;LTSTagsLocalized&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    lTSTags?: any;
    /**
     * 
     * @type {string}
     * @memberof GBLTSActivityPoiLocalized
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    active?: any;
    /**
     * 
     * @type {string}
     * @memberof GBLTSActivityPoiLocalized
     */
    shortname?: any;
    /**
     * 
     * @type {string}
     * @memberof GBLTSActivityPoiLocalized
     */
    smgId?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    highlight?: any;
    /**
     * 
     * @type {string}
     * @memberof GBLTSActivityPoiLocalized
     */
    difficulty?: any;
    /**
     * 
     * @type {string}
     * @memberof GBLTSActivityPoiLocalized
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof GBLTSActivityPoiLocalized
     */
    subType?: any;
    /**
     * 
     * @type {Date}
     * @memberof GBLTSActivityPoiLocalized
     */
    firstImport?: any;
    /**
     * 
     * @type {Date}
     * @memberof GBLTSActivityPoiLocalized
     */
    lastChange?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    smgActive?: any;
    /**
     * 
     * @type {LocationInfoLocalized}
     * @memberof GBLTSActivityPoiLocalized
     */
    locationInfo?: any;
    /**
     * 
     * @type {string}
     * @memberof GBLTSActivityPoiLocalized
     */
    tourismorganizationId?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    areaId?: any;
    /**
     * 
     * @type {number}
     * @memberof GBLTSActivityPoiLocalized
     */
    altitudeDifference?: any;
    /**
     * 
     * @type {number}
     * @memberof GBLTSActivityPoiLocalized
     */
    altitudeHighestPoint?: any;
    /**
     * 
     * @type {number}
     * @memberof GBLTSActivityPoiLocalized
     */
    altitudeLowestPoint?: any;
    /**
     * 
     * @type {number}
     * @memberof GBLTSActivityPoiLocalized
     */
    altitudeSumUp?: any;
    /**
     * 
     * @type {number}
     * @memberof GBLTSActivityPoiLocalized
     */
    altitudeSumDown?: any;
    /**
     * 
     * @type {number}
     * @memberof GBLTSActivityPoiLocalized
     */
    distanceDuration?: any;
    /**
     * 
     * @type {number}
     * @memberof GBLTSActivityPoiLocalized
     */
    distanceLength?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    isOpen?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    isPrepared?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    runToValley?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    isWithLigth?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    hasRentals?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    hasFreeEntrance?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    liftAvailable?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    feetClimb?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GBLTSActivityPoiLocalized
     */
    bikeTransport?: any;
    /**
     * 
     * @type {Array&lt;OperationSchedule&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    operationSchedule?: any;
    /**
     * 
     * @type {Array&lt;GpsInfo&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    gpsInfo?: any;
    /**
     * 
     * @type {Array&lt;GpsTrack&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    gpsTrack?: any;
    /**
     * 
     * @type {Array&lt;ImageGalleryLocalized&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    imageGallery?: any;
    /**
     * 
     * @type {Detail}
     * @memberof GBLTSActivityPoiLocalized
     */
    detail?: any;
    /**
     * 
     * @type {ContactInfos}
     * @memberof GBLTSActivityPoiLocalized
     */
    contactInfos?: any;
    /**
     * 
     * @type {AdditionalPoiInfos}
     * @memberof GBLTSActivityPoiLocalized
     */
    additionalPoiInfos?: any;
    /**
     * 
     * @type {Ratings}
     * @memberof GBLTSActivityPoiLocalized
     */
    ratings?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    exposition?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof GBLTSActivityPoiLocalized
     */
    smgTags?: any;
}
