/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImageGallery
 */
export interface ImageGallery {
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    imageName?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    imageUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof ImageGallery
     */
    width?: any;
    /**
     * 
     * @type {number}
     * @memberof ImageGallery
     */
    height?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    imageSource?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof ImageGallery
     */
    imageTitle?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof ImageGallery
     */
    imageDesc?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof ImageGallery
     */
    imageAltText?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ImageGallery
     */
    isInGallery?: any;
    /**
     * 
     * @type {number}
     * @memberof ImageGallery
     */
    listPosition?: any;
    /**
     * 
     * @type {Date}
     * @memberof ImageGallery
     */
    validFrom?: any;
    /**
     * 
     * @type {Date}
     * @memberof ImageGallery
     */
    validTo?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    copyRight?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    license?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    licenseHolder?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ImageGallery
     */
    imageTags?: any;
}
