/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ratings
 */
export interface Ratings {
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    stamina?: any;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    experience?: any;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    landscape?: any;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    difficulty?: any;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    technique?: any;
}
