/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SkiAreaLocalized
 */
export interface SkiAreaLocalized {
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    skiRegionId?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    skiAreaMapURL?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    totalSlopeKm?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    slopeKmBlue?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    slopeKmRed?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    slopeKmBlack?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    liftCount?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiAreaLocalized
     */
    altitudeFrom?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiAreaLocalized
     */
    altitudeTo?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    skiRegionName?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiAreaLocalized
     */
    areaId?: any;
    /**
     * 
     * @type {Array&lt;WebcamLocalized&gt;}
     * @memberof SkiAreaLocalized
     */
    webcam?: any;
    /**
     * 
     * @type {LocationInfoLocalized}
     * @memberof SkiAreaLocalized
     */
    locationInfo?: any;
    /**
     * 
     * @type {Array&lt;OperationSchedule&gt;}
     * @memberof SkiAreaLocalized
     */
    operationSchedule?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiAreaLocalized
     */
    tourismvereinIds?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiAreaLocalized
     */
    regionIds?: any;
    /**
     * 
     * @type {Array&lt;GpsPolygon&gt;}
     * @memberof SkiAreaLocalized
     */
    gpsPolygon?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SkiAreaLocalized
     */
    active?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    customId?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    shortname?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    gpstype?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiAreaLocalized
     */
    latitude?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiAreaLocalized
     */
    longitude?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiAreaLocalized
     */
    altitude?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLocalized
     */
    altitudeUnitofMeasure?: any;
    /**
     * 
     * @type {Detail}
     * @memberof SkiAreaLocalized
     */
    detail?: any;
    /**
     * 
     * @type {ContactInfos}
     * @memberof SkiAreaLocalized
     */
    contactInfos?: any;
    /**
     * 
     * @type {Array&lt;ImageGalleryLocalized&gt;}
     * @memberof SkiAreaLocalized
     */
    imageGallery?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiAreaLocalized
     */
    smgTags?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SkiAreaLocalized
     */
    smgActive?: any;
}
