/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SkiArea
 */
export interface SkiArea {
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    skiRegionId?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    skiAreaMapURL?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    totalSlopeKm?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    slopeKmBlue?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    slopeKmRed?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    slopeKmBlack?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    liftCount?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiArea
     */
    altitudeFrom?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiArea
     */
    altitudeTo?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof SkiArea
     */
    skiRegionName?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiArea
     */
    areaId?: any;
    /**
     * 
     * @type {Array&lt;Webcam&gt;}
     * @memberof SkiArea
     */
    webcam?: any;
    /**
     * 
     * @type {LocationInfo}
     * @memberof SkiArea
     */
    locationInfo?: any;
    /**
     * 
     * @type {Array&lt;OperationSchedule&gt;}
     * @memberof SkiArea
     */
    operationSchedule?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiArea
     */
    tourismvereinIds?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiArea
     */
    regionIds?: any;
    /**
     * 
     * @type {Array&lt;GpsPolygon&gt;}
     * @memberof SkiArea
     */
    gpsPolygon?: any;
    /**
     * 
     * @type {Array&lt;RelatedContent&gt;}
     * @memberof SkiArea
     */
    relatedContent?: any;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof SkiArea
     */
    licenseInfo?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SkiArea
     */
    active?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    customId?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    shortname?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    gpstype?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiArea
     */
    latitude?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiArea
     */
    longitude?: any;
    /**
     * 
     * @type {number}
     * @memberof SkiArea
     */
    altitude?: any;
    /**
     * 
     * @type {string}
     * @memberof SkiArea
     */
    altitudeUnitofMeasure?: any;
    /**
     * 
     * @type {{ [key, string]: Detail;}}
     * @memberof SkiArea
     */
    detail?: any;
    /**
     * 
     * @type {{ [key, string]: ContactInfos;}}
     * @memberof SkiArea
     */
    contactInfos?: any;
    /**
     * 
     * @type {Array&lt;ImageGallery&gt;}
     * @memberof SkiArea
     */
    imageGallery?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiArea
     */
    smgTags?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SkiArea
     */
    smgActive?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SkiArea
     */
    hasLanguage?: any;
    /**
     * 
     * @type {Date}
     * @memberof SkiArea
     */
    lastChange?: any;
}
