// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SmgPoiTypes
 */
 export interface SmgPoiTypes {
    /**
     * 
     * @type {string}
     * @memberof SmgPoiTypes
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof SmgPoiTypes
     */
    bitmask?: any;
    /**
     * 
     * @type {string}
     * @memberof SmgPoiTypes
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof SmgPoiTypes
     */
    parent?: any;
    /**
     * 
     * @type {string}
     * @memberof SmgPoiTypes
     */
    key?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof SmgPoiTypes
     */
    typeDesc?: any;
}