/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SmgTags
 */
export interface SmgTags {
    /**
     * 
     * @type {string}
     * @memberof SmgTags
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof SmgTags
     */
    shortname?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof SmgTags
     */
    tagName?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SmgTags
     */
    validForEntity?: any;
    /**
     * 
     * @type {string}
     * @memberof SmgTags
     */
    mainEntity?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SmgTags
     */
    source?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof SmgTags
     */
    iDMCategoryMapping?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SmgTags
     */
    displayAsCategory?: any;
}
