/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SnowReportBaseData
 */
export interface SnowReportBaseData {
    /**
     * 
     * @type {number}
     * @memberof SnowReportBaseData
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    RID?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    skiregion?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    areaname?: any;
    /**
     * 
     * @type {Date}
     * @memberof SnowReportBaseData
     */
    lastUpdate?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    lang?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    skiAreaSlopeKm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    skiMapUrl?: any;
    /**
     * 
     * @type {Array&lt;MeasuringpointReduced&gt;}
     * @memberof SnowReportBaseData
     */
    measuringpoints?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SnowReportBaseData
     */
    webcamUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskilift?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskilift?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskiliftkm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskiliftkm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskislopes?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskislopes?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskislopeskm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskislopeskm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totaltracks?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentracks?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totaltrackskm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentrackskm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalslides?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentslides?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalslideskm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentslideskm?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totaliceskating?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openiceskating?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactadress?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contacttel?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactcap?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactcity?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactfax?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactweburl?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactmail?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactlogo?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactgpsnorth?: any;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactgpseast?: any;
}
