/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Tourismverein
 */
export interface Tourismverein {
    /**
     * 
     * @type {string}
     * @memberof Tourismverein
     */
    regionId?: any;
    /**
     * 
     * @type {Array&lt;GpsPolygon&gt;}
     * @memberof Tourismverein
     */
    gpsPolygon?: any;
    /**
     * 
     * @type {Array&lt;Webcam&gt;}
     * @memberof Tourismverein
     */
    webcam?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Tourismverein
     */
    visibleInSearch?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Tourismverein
     */
    skiareaIds?: any;
    /**
     * 
     * @type {Array&lt;RelatedContent&gt;}
     * @memberof Tourismverein
     */
    relatedContent?: any;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof Tourismverein
     */
    licenseInfo?: any;
    /**
     * 
     * @type {string}
     * @memberof Tourismverein
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Tourismverein
     */
    active?: any;
    /**
     * 
     * @type {string}
     * @memberof Tourismverein
     */
    customId?: any;
    /**
     * 
     * @type {string}
     * @memberof Tourismverein
     */
    shortname?: any;
    /**
     * 
     * @type {string}
     * @memberof Tourismverein
     */
    gpstype?: any;
    /**
     * 
     * @type {number}
     * @memberof Tourismverein
     */
    latitude?: any;
    /**
     * 
     * @type {number}
     * @memberof Tourismverein
     */
    longitude?: any;
    /**
     * 
     * @type {number}
     * @memberof Tourismverein
     */
    altitude?: any;
    /**
     * 
     * @type {string}
     * @memberof Tourismverein
     */
    altitudeUnitofMeasure?: any;
    /**
     * 
     * @type {{ [key, string]: Detail;}}
     * @memberof Tourismverein
     */
    detail?: any;
    /**
     * 
     * @type {{ [key, string]: ContactInfos;}}
     * @memberof Tourismverein
     */
    contactInfos?: any;
    /**
     * 
     * @type {Array&lt;ImageGallery&gt;}
     * @memberof Tourismverein
     */
    imageGallery?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Tourismverein
     */
    smgTags?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Tourismverein
     */
    smgActive?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Tourismverein
     */
    hasLanguage?: any;
    /**
     * 
     * @type {Date}
     * @memberof Tourismverein
     */
    lastChange?: any;
}
