/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VenueRoomDetails
 */
export interface VenueRoomDetails {
    /**
     * 
     * @type {string}
     * @memberof VenueRoomDetails
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof VenueRoomDetails
     */
    shortname?: any;
    /**
     * 
     * @type {number}
     * @memberof VenueRoomDetails
     */
    squareMeters?: any;
    /**
     * 
     * @type {boolean}
     * @memberof VenueRoomDetails
     */
    indoor?: any;
    /**
     * 
     * @type {Array&lt;VenueType&gt;}
     * @memberof VenueRoomDetails
     */
    venueFeatures?: any;
    /**
     * 
     * @type {Array&lt;VenueSetup&gt;}
     * @memberof VenueRoomDetails
     */
    venueSetup?: any;
}
