/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Weather
 */
export interface Weather {
    /**
     * 
     * @type {number}
     * @memberof Weather
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof Weather
     */
    date?: any;
    /**
     * 
     * @type {string}
     * @memberof Weather
     */
    evolutiontitle?: any;
    /**
     * 
     * @type {string}
     * @memberof Weather
     */
    evolution?: any;
    /**
     * 
     * @type {Array&lt;Conditions&gt;}
     * @memberof Weather
     */
    conditions?: any;
    /**
     * 
     * @type {Array&lt;Forecast&gt;}
     * @memberof Weather
     */
    forecast?: any;
    /**
     * 
     * @type {Array&lt;Mountain&gt;}
     * @memberof Weather
     */
    mountain?: any;
    /**
     * 
     * @type {Array&lt;Stationdata&gt;}
     * @memberof Weather
     */
    stationdata?: any;
}
