/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WebcamLocalized
 */
export interface WebcamLocalized {
    /**
     * 
     * @type {string}
     * @memberof WebcamLocalized
     */
    webcamId?: any;
    /**
     * 
     * @type {string}
     * @memberof WebcamLocalized
     */
    webcamname?: any;
    /**
     * 
     * @type {string}
     * @memberof WebcamLocalized
     */
    webcamurl?: any;
    /**
     * 
     * @type {GpsInfo}
     * @memberof WebcamLocalized
     */
    gpsInfo?: any;
    /**
     * 
     * @type {number}
     * @memberof WebcamLocalized
     */
    listPosition?: any;
}
